# GENERATED by make_pyunitt.py with step1_read_print.mal as input

import unittest
import repl
import printer

class REPLTest(unittest.TestCase):
    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test0(self):
        assert(repl.test_repl("1") == "1")

    def test1(self):
        assert(repl.test_repl("7") == "7")

    def test2(self):
        assert(repl.test_repl("  7   ") == "7")

    def test3(self):
        assert(repl.test_repl("-123") == "-123")

    def test4(self):
        assert(repl.test_repl("+") == "+")

    def test5(self):
        assert(repl.test_repl("abc") == "abc")

    def test6(self):
        assert(repl.test_repl("   abc   ") == "abc")

    def test7(self):
        assert(repl.test_repl("abc5") == "abc5")

    def test8(self):
        assert(repl.test_repl("abc-def") == "abc-def")

    def test9(self):
        assert(repl.test_repl("-") == "-")

    def test10(self):
        assert(repl.test_repl("-abc") == "-abc")

    def test11(self):
        assert(repl.test_repl("->>") == "->>")

    def test12(self):
        assert(repl.test_repl("(+ 1 2)") == "(+ 1 2)")

    def test13(self):
        assert(repl.test_repl("()") == "()")

    def test14(self):
        assert(repl.test_repl("( )") == "()")

    def test15(self):
        assert(repl.test_repl("(nil)") == "(nil)")

    def test16(self):
        assert(repl.test_repl("((3 4))") == "((3 4))")

    def test17(self):
        assert(repl.test_repl("(+ 1 (+ 2 3))") == "(+ 1 (+ 2 3))")

    def test18(self):
        assert(repl.test_repl("  ( +   1   (+   2 3   )   )  ") == "(+ 1 (+ 2 3))")

    def test19(self):
        assert(repl.test_repl("(* 1 2)") == "(* 1 2)")

    def test20(self):
        assert(repl.test_repl("(** 1 2)") == "(** 1 2)")

    def test21(self):
        assert(repl.test_repl("(* -3 6)") == "(* -3 6)")

    def test22(self):
        assert(repl.test_repl("(()())") == "(() ())")

    def test23(self):
        assert(repl.test_repl("(1 2, 3,,,,),,") == "(1 2 3)")

if __name__ == "__main__":
    unittest.main()
